export const STYLES = {
  font: {
    headline_1: {
      'font-family': 'Noto Sans KR',
      'font-size': '46px',
      'font-weight': '700',
      'line-height': '64px',
      'letter-spacing': '-0.4px',
    },
    headline_2: {
      'font-family': 'Noto Sans KR',
      'font-size': '42px',
      'font-weight': '700',
      'line-height': '60px',
      'letter-spacing': '-0.4px',
    },
    headline_3: {
      'font-family': 'Noto Sans KR',
      'font-size': '34px',
      'font-weight': '700',
      'line-height': '52px',
      'letter-spacing': '-0.4px',
    },
    headline_4: {
      'font-family': 'Noto Sans KR',
      'font-size': '28px',
      'font-weight': '700',
      'line-height': '40px',
      'letter-spacing': '-0.4px',
    },
    headline_5: {
      'font-family': 'Noto Sans KR',
      'font-size': '24px',
      'font-weight': '700',
      'line-height': '34px',
      'letter-spacing': '-0.4px',
    },
    subtitle_1: {
      'font-family': 'Noto Sans KR',
      'font-size': '16px',
      'font-weight': '700',
      'line-height': '24px',
      'letter-spacing': '-0.2px',
    },
    subtitle_2: {
      'font-family': 'Noto Sans KR',
      'font-size': '14px',
      'font-weight': '700',
      'line-height': '22px',
      'letter-spacing': '-0.2px',
    },
    body_1: {
      'font-family': 'Noto Sans KR',
      'font-size': '16px',
      'font-weight': '400',
      'line-height': '24px',
      'letter-spacing': '-0.4px',
    },
    body_2: {
      'font-family': 'Noto Sans KR',
      'font-size': '15px',
      'font-weight': '400',
      'line-height': '23px',
      'letter-spacing': '-0.4px',
    },
    button_1: {
      'font-family': 'Noto Sans KR',
      'font-size': '16px',
      'font-weight': '500',
      'line-height': '24px',
    },
    button_2: {
      'font-family': 'Noto Sans KR',
      'font-size': '14px',
      'font-weight': '500',
      'line-height': '22px',
    },
  },
  color: {
    primary_500: '#0f90e9',
    primary_400: '#269beb',
    primary_300: '#3ea6ed',
    primary_200: '#57b1ef',
    primary_100: '#6fbcf1',
    primary_50: '#87c7f4',

    secondary_500: '#28c596',
    secondary_400: '#3dd7a9',
    secondary_300: '#52edbf',
    secondary_200: '#67fdd0',
    secondary_100: '#beffee',
    secondary_50: '#edfffa',

    greyscale_950: '#0d0d0d',
    greyscale_900: '#1a1a1a',
    greyscale_800: '#333333',
    greyscale_700: '#4d4d4d',
    greyscale_600: '#666666',
    greyscale_500: '#808080',
    greyscale_400: '#999999',
    greyscale_300: '#b3b3b3',
    greyscale_200: '#cccccc',
    greyscale_100: '#e5e5e5',
    greyscale_50: '#f2f2f2',
    greyscale_25: '#f9f9f9',

    white: '#FAFAFA',
  },
};
